# coding: utf-8

"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mixedbread_ai.models.embeddings200_response_data_inner import Embeddings200ResponseDataInner

class TestEmbeddings200ResponseDataInner(unittest.TestCase):
    """Embeddings200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embeddings200ResponseDataInner:
        """Test Embeddings200ResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embeddings200ResponseDataInner`
        """
        model = Embeddings200ResponseDataInner()
        if include_optional:
            return Embeddings200ResponseDataInner(
                embedding = [
                    1.337
                    ],
                index = 56,
                was_truncated = True
            )
        else:
            return Embeddings200ResponseDataInner(
        )
        """

    def testEmbeddings200ResponseDataInner(self):
        """Test Embeddings200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
