# coding: utf-8

"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mixedbread_ai.models.embeddings200_response import Embeddings200Response

class TestEmbeddings200Response(unittest.TestCase):
    """Embeddings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embeddings200Response:
        """Test Embeddings200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embeddings200Response`
        """
        model = Embeddings200Response()
        if include_optional:
            return Embeddings200Response(
                model = '',
                data = [
                    mixedbread_ai.models.embeddings_200_response_data_inner.embeddings_200_response_data_inner(
                        embedding = [
                            1.337
                            ], 
                        index = 56, 
                        was_truncated = True, )
                    ],
                usage = mixedbread_ai.models.embeddings_200_response_usage.embeddings_200_response_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, )
            )
        else:
            return Embeddings200Response(
                model = '',
                data = [
                    mixedbread_ai.models.embeddings_200_response_data_inner.embeddings_200_response_data_inner(
                        embedding = [
                            1.337
                            ], 
                        index = 56, 
                        was_truncated = True, )
                    ],
                usage = mixedbread_ai.models.embeddings_200_response_usage.embeddings_200_response_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, ),
        )
        """

    def testEmbeddings200Response(self):
        """Test Embeddings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
