# coding: utf-8

"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mixedbread_ai.models.embeddings200_response_usage import Embeddings200ResponseUsage

class TestEmbeddings200ResponseUsage(unittest.TestCase):
    """Embeddings200ResponseUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embeddings200ResponseUsage:
        """Test Embeddings200ResponseUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embeddings200ResponseUsage`
        """
        model = Embeddings200ResponseUsage()
        if include_optional:
            return Embeddings200ResponseUsage(
                prompt_tokens = 56,
                total_tokens = 56
            )
        else:
            return Embeddings200ResponseUsage(
        )
        """

    def testEmbeddings200ResponseUsage(self):
        """Test Embeddings200ResponseUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
