# coding: utf-8

"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mixedbread_ai.models.embeddings_response import EmbeddingsResponse

class TestEmbeddingsResponse(unittest.TestCase):
    """EmbeddingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbeddingsResponse:
        """Test EmbeddingsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbeddingsResponse`
        """
        model = EmbeddingsResponse()
        if include_optional:
            return EmbeddingsResponse(
                normalized = True,
                data = [
                    mixedbread_ai.models.embedding.Embedding(
                        embedding = [
                            1.337
                            ], 
                        index = 56, 
                        truncated = True, )
                    ],
                model = '',
                usage = mixedbread_ai.models.embeddings_response_usage.EmbeddingsResponse_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, 
                    completion_tokens = 56, )
            )
        else:
            return EmbeddingsResponse(
                normalized = True,
                data = [
                    mixedbread_ai.models.embedding.Embedding(
                        embedding = [
                            1.337
                            ], 
                        index = 56, 
                        truncated = True, )
                    ],
                model = '',
                usage = mixedbread_ai.models.embeddings_response_usage.EmbeddingsResponse_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, 
                    completion_tokens = 56, ),
        )
        """

    def testEmbeddingsResponse(self):
        """Test EmbeddingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
