# coding: utf-8

"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixedbread_ai.api.mixedbread_ai_api import MixedbreadAiApi


class TestMixedbreadAiApi(unittest.TestCase):
    """MixedbreadAiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MixedbreadAiApi()

    def tearDown(self) -> None:
        pass

    def test_embeddings(self) -> None:
        """Test case for embeddings

        Create embeddings
        """
        pass


if __name__ == '__main__':
    unittest.main()
