# coding: utf-8

# flake8: noqa
"""
    mixedbread-ai

    Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from mixedbread_ai.models.embeddings200_response import Embeddings200Response
from mixedbread_ai.models.embeddings200_response_data_inner import Embeddings200ResponseDataInner
from mixedbread_ai.models.embeddings200_response_usage import Embeddings200ResponseUsage
from mixedbread_ai.models.embeddings_request import EmbeddingsRequest
from mixedbread_ai.models.error_response import ErrorResponse
