# This file was auto-generated by Fern from our API Definition.

import typing

from .embedding import Embedding
from .multi_encodings_embedding import MultiEncodingsEmbedding

Data = typing.Union[typing.List[Embedding], typing.List[MultiEncodingsEmbedding]]
