# This file was auto-generated by Fern from our API Definition.

import typing

from .embedding import Embedding
from .multiple_encodings_embedding import MultipleEncodingsEmbedding

Data = typing.Union[typing.List[Embedding], typing.List[MultipleEncodingsEmbedding]]
