# This file was auto-generated by Fern from our API Definition.

import typing

from .encoding_format import EncodingFormat

EmbeddingsRequestEncodingFormat = typing.Union[EncodingFormat, typing.List[EncodingFormat]]
