# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EncodingFormat(str, enum.Enum):
    FLOAT = "float"
    BASE_64 = "base64"
    BINARY = "binary"
    UBINARY = "ubinary"
    INT_8 = "int8"
    UINT_8 = "uint8"

    def visit(
        self,
        float_: typing.Callable[[], T_Result],
        base_64: typing.Callable[[], T_Result],
        binary: typing.Callable[[], T_Result],
        ubinary: typing.Callable[[], T_Result],
        int_8: typing.Callable[[], T_Result],
        uint_8: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EncodingFormat.FLOAT:
            return float_()
        if self is EncodingFormat.BASE_64:
            return base_64()
        if self is EncodingFormat.BINARY:
            return binary()
        if self is EncodingFormat.UBINARY:
            return ubinary()
        if self is EncodingFormat.INT_8:
            return int_8()
        if self is EncodingFormat.UINT_8:
            return uint_8()
