# This file was auto-generated by Fern from our API Definition.

import typing

from .text_document import TextDocument

Input = typing.Union[str, typing.List[str], TextDocument, typing.List[TextDocument]]
