# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .multiple_encodings_embedding_item import MultipleEncodingsEmbeddingItem
from .object_type import ObjectType


class MultipleEncodingsEmbedding(pydantic_v1.BaseModel):
    embedding: MultipleEncodingsEmbeddingItem = pydantic_v1.Field()
    """
    The encoded embedding data by encoding format. Returned, if more than one encoding format is used.
    """

    index: int = pydantic_v1.Field()
    """
    The index of the embedding
    """

    object: typing.Optional[ObjectType] = pydantic_v1.Field(default=None)
    """
    The object type of the embedding
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
