# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1


class MultipleEncodingsEmbeddingItem(pydantic_v1.BaseModel):
    float_: typing.Optional[typing.List[float]] = pydantic_v1.Field(alias="float", default=None)
    int_8: typing.Optional[typing.List[int]] = pydantic_v1.Field(alias="int8", default=None)
    uint_8: typing.Optional[typing.List[int]] = pydantic_v1.Field(alias="uint8", default=None)
    binary: typing.Optional[typing.List[int]] = None
    ubinary: typing.Optional[typing.List[int]] = None
    base_64: typing.Optional[typing.List[str]] = pydantic_v1.Field(alias="base64", default=None)

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
