# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .invalid_matryoshka_dimensions_error import InvalidMatryoshkaDimensionsError
from .invalid_matryoshka_model_error import InvalidMatryoshkaModelError
from .model_not_found_error import ModelNotFoundError
from .validation_error import ValidationError
from .web_truncation_error import WebTruncationError


class UnprocessableEntityErrorBody_ValidationError(ValidationError):
    type: typing_extensions.Literal["ValidationError"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class UnprocessableEntityErrorBody_ModelNotFoundError(ModelNotFoundError):
    type: typing_extensions.Literal["ModelNotFoundError"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class UnprocessableEntityErrorBody_WebTruncationError(WebTruncationError):
    type: typing_extensions.Literal["WebTruncationError"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class UnprocessableEntityErrorBody_InvalidMatryoshkaModelError(InvalidMatryoshkaModelError):
    type: typing_extensions.Literal["InvalidMatryoshkaModelError"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class UnprocessableEntityErrorBody_InvalidMatryoshkaDimensionsError(InvalidMatryoshkaDimensionsError):
    type: typing_extensions.Literal["InvalidMatryoshkaDimensionsError"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


UnprocessableEntityErrorBody = typing.Union[
    UnprocessableEntityErrorBody_ValidationError,
    UnprocessableEntityErrorBody_ModelNotFoundError,
    UnprocessableEntityErrorBody_WebTruncationError,
    UnprocessableEntityErrorBody_InvalidMatryoshkaModelError,
    UnprocessableEntityErrorBody_InvalidMatryoshkaDimensionsError,
]
